/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardNewAssessmentRouteImport } from './routes/dashboard/new-assessment'
import { Route as DashboardKnowledgeGraphRouteImport } from './routes/dashboard/knowledge-graph'
import { Route as DashboardFarmerProfilesRouteImport } from './routes/dashboard/farmer-profiles'
import { Route as DashboardClimateInsightsRouteImport } from './routes/dashboard/climate-insights'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardAiAssessmentsRouteImport } from './routes/dashboard/ai-assessments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewAssessmentRoute = DashboardNewAssessmentRouteImport.update({
  id: '/dashboard/new-assessment',
  path: '/dashboard/new-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKnowledgeGraphRoute = DashboardKnowledgeGraphRouteImport.update({
  id: '/dashboard/knowledge-graph',
  path: '/dashboard/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFarmerProfilesRoute = DashboardFarmerProfilesRouteImport.update({
  id: '/dashboard/farmer-profiles',
  path: '/dashboard/farmer-profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClimateInsightsRoute =
  DashboardClimateInsightsRouteImport.update({
    id: '/dashboard/climate-insights',
    path: '/dashboard/climate-insights',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/dashboard/applications',
  path: '/dashboard/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiAssessmentsRoute = DashboardAiAssessmentsRouteImport.update({
  id: '/dashboard/ai-assessments',
  path: '/dashboard/ai-assessments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/ai-assessments': typeof DashboardAiAssessmentsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/climate-insights': typeof DashboardClimateInsightsRoute
  '/dashboard/farmer-profiles': typeof DashboardFarmerProfilesRoute
  '/dashboard/knowledge-graph': typeof DashboardKnowledgeGraphRoute
  '/dashboard/new-assessment': typeof DashboardNewAssessmentRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-assessments': typeof DashboardAiAssessmentsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/climate-insights': typeof DashboardClimateInsightsRoute
  '/dashboard/farmer-profiles': typeof DashboardFarmerProfilesRoute
  '/dashboard/knowledge-graph': typeof DashboardKnowledgeGraphRoute
  '/dashboard/new-assessment': typeof DashboardNewAssessmentRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/ai-assessments': typeof DashboardAiAssessmentsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/climate-insights': typeof DashboardClimateInsightsRoute
  '/dashboard/farmer-profiles': typeof DashboardFarmerProfilesRoute
  '/dashboard/knowledge-graph': typeof DashboardKnowledgeGraphRoute
  '/dashboard/new-assessment': typeof DashboardNewAssessmentRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/ai-assessments'
    | '/dashboard/applications'
    | '/dashboard/climate-insights'
    | '/dashboard/farmer-profiles'
    | '/dashboard/knowledge-graph'
    | '/dashboard/new-assessment'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-assessments'
    | '/dashboard/applications'
    | '/dashboard/climate-insights'
    | '/dashboard/farmer-profiles'
    | '/dashboard/knowledge-graph'
    | '/dashboard/new-assessment'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard/ai-assessments'
    | '/dashboard/applications'
    | '/dashboard/climate-insights'
    | '/dashboard/farmer-profiles'
    | '/dashboard/knowledge-graph'
    | '/dashboard/new-assessment'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAiAssessmentsRoute: typeof DashboardAiAssessmentsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardClimateInsightsRoute: typeof DashboardClimateInsightsRoute
  DashboardFarmerProfilesRoute: typeof DashboardFarmerProfilesRoute
  DashboardKnowledgeGraphRoute: typeof DashboardKnowledgeGraphRoute
  DashboardNewAssessmentRoute: typeof DashboardNewAssessmentRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new-assessment': {
      id: '/dashboard/new-assessment'
      path: '/dashboard/new-assessment'
      fullPath: '/dashboard/new-assessment'
      preLoaderRoute: typeof DashboardNewAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/knowledge-graph': {
      id: '/dashboard/knowledge-graph'
      path: '/dashboard/knowledge-graph'
      fullPath: '/dashboard/knowledge-graph'
      preLoaderRoute: typeof DashboardKnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/farmer-profiles': {
      id: '/dashboard/farmer-profiles'
      path: '/dashboard/farmer-profiles'
      fullPath: '/dashboard/farmer-profiles'
      preLoaderRoute: typeof DashboardFarmerProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/climate-insights': {
      id: '/dashboard/climate-insights'
      path: '/dashboard/climate-insights'
      fullPath: '/dashboard/climate-insights'
      preLoaderRoute: typeof DashboardClimateInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/dashboard/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-assessments': {
      id: '/dashboard/ai-assessments'
      path: '/dashboard/ai-assessments'
      fullPath: '/dashboard/ai-assessments'
      preLoaderRoute: typeof DashboardAiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAiAssessmentsRoute: DashboardAiAssessmentsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardClimateInsightsRoute: DashboardClimateInsightsRoute,
  DashboardFarmerProfilesRoute: DashboardFarmerProfilesRoute,
  DashboardKnowledgeGraphRoute: DashboardKnowledgeGraphRoute,
  DashboardNewAssessmentRoute: DashboardNewAssessmentRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
